server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brad-zhou/config-files/
          username: your-name
          password: your-password
          search-paths: '{application}' # Placeholder - searches the repository for files in the same name as the directory
      label: master
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/